# Generated by Django 5.1.1 on 2024-10-28 22:32

import myportal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprint',
            name='blueprint_type',
            field=models.CharField(choices=[('mechanical', 'Mechanical'), ('electrical', 'Electrical'), ('software', 'Software'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='file',
            field=models.FileField(upload_to=myportal.models.blueprint_upload_to),
        ),
    ]
